- name: Install XFCE Desktop
  apt:
    install_recommends: no
    state: present
    name:
      - xubuntu-desktop
  when: "installing == true"
  notify: reboot

- name: Hide provision user from login
  include_role:
    name: lightdm_hide_user
  vars:
    user: "{{ provision_user }}"
  when: "installing"

- name: Remove provision user login file
  include_role:
    name: lightdm_hide_user
  vars:
    user: "{{ provision_user }}"
    remove: yes
  when: "not installing"


- name: Remove XFCE Desktop
  apt:
    state: absent
    autoremove: yes
    name:
      - xubuntu-desktop
  when: "installing == false"
  notify: reboot
