- name: Install XFCE Desktop
  apt:
    install_recommends: no
    state: present
    name:
      - xubuntu-desktop
  when: "installing == true"
  notify: reboot

- name: Remove XFCE Desktop
  apt:
    state: absent
    autoremove: yes
    name:
      - xubuntu-desktop
  when: "installing == false"
  notify: reboot
