# - name: Dependencies
#   apt:
#     pkg:
#     - apt-transport-https
#     state: latest
#     force_apt_get: yes
#     update_cache: no
#   when: installing

- name: Add Docker Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Source
  shell: source /etc/os-release && echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu ${UBUNTU_CODENAME} stable " > /etc/apt/sources.list.d/docker-${UBUNTU_CODENAME}.list
  args:
    executable: /bin/bash

- name: Install Docker
  apt:
    pkg:
    - docker-ce
    - docker-compose
    state: latest
    force_apt_get: yes
    update_cache: yes

- name: Add Docker Daemon Config
  template:
    src: templates/daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: u+r
  notify:
    - restart docker
