# - name: Dependencies
#   apt:
#     pkg:
#     - apt-transport-https
#     state: latest
#     force_apt_get: yes
#     update_cache: no
#   when: installing
# TODO
# FIX Docker Compose Install (APT pacahges it with a bad dep)
#sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#sudo chmod +x /usr/local/bin/docker-compose

- name: Add Docker Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Source
  shell: source /etc/os-release && echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu ${UBUNTU_CODENAME} stable " > /etc/apt/sources.list.d/docker-${UBUNTU_CODENAME}.list
  args:
    executable: /bin/bash

- name: Install Docker
  apt:
    pkg:
    - docker-ce
    state: latest
    force_apt_get: yes
    update_cache: yes
  notify: docker | restart

- name: Add Docker Daemon Config
  template:
    src: templates/daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: u+r
  notify: docker | restart
