# - name: Display all variables/facts known for a host
#   debug:
#     var: hostvars[inventory_hostname]

- name: Install XFCE Desktop
  apt:
    install_recommends: no
    state: present
    name:
      - xubuntu-desktop
  when: "hostvars[inventory_hostname]['feature_xfce_desktop'] == true"
  notify: reboot

- name: Remove XFCE Desktop
  apt:
    state: absent
    autoremove: yes
    name:
      - xubuntu-desktop
  when: "hostvars[inventory_hostname]['feature_xfce_desktop'] == false"
  notify: reboot
