

- name: Check if Cert Key Exists
  stat:
    path: "/etc/letsencrypt/live/{{reverse_proxy_certbot_domain}}/privkey.pem"
  register: cert_stat_reverse_proxy_certbot

- name: Shut Off Reverse Proxy
  command: "docker-compose -f {{reverse_proxy_certbot_compose_file_path}} down"
  when: not cert_stat_reverse_proxy_certbot.stat.exists or reverse_proxy_certbot_renew

- name: Create Cert if it does not exist
  include_role:
    name: certbot_ssl_cert
  vars:
    certbot_ssl_cert_domain: "{{reverse_proxy_certbot_domain}}"
    certbot_ssl_cert_renew: no
    certbot_ssl_cert_email: "{{reverse_proxy_certbot_email}}"
  when: not cert_stat_reverse_proxy_certbot.stat.exists

- name: Create Cert if it does not exist
  include_role:
    name: certbot_ssl_cert
  vars:
    certbot_ssl_cert_domain: "{{reverse_proxy_certbot_domain}}"
    certbot_ssl_cert_renew: yes
    certbot_ssl_cert_email: "{{reverse_proxy_certbot_email}}"
  when: cert_stat_reverse_proxy_certbot.stat.exists and reverse_proxy_certbot_renew

- name: Turn On Reverse Proxy
  command: "docker-compose -f {{reverse_proxy_certbot_compose_file_path}} up -d"
  when: not cert_stat_reverse_proxy_certbot.stat.exists or reverse_proxy_certbot_renew
