- name: Install Samba
  apt:
    name: samba
    state: latest
    force_apt_get: yes
    update_cache: no
  notify:
    - smbd | restart

- name: Add Mount Groups
  group:
    name: "{{ item.group }}"
    state: present
    system: no
    gid: "{{ item.gid }}"
  loop: "{{ samba_server_shares | maplistwithlistlookup('group', samba_server_share_groups, 'group') }}"

- name: Add Share Groups
  group:
    name: "{{ item.group }}"
    state: present
    system: no
    gid: "{{ item.gid }}"
  loop: "{{ samba_server_shares | reversemultimap('path', 'users', 'user') | map(attribute='user') | maplistwithlistlookup('user', samba_server_share_users, 'user') }}"
#TODO Add share group to users in share list
- name: Add Share Users
  user:
    group: "{{ item.group }}"
    uid: "{{ item.uid }}"
    name: "{{ item.user }}"
    create_home: false
    shell: /bin/bash
    state: present
    system: no
  loop: "{{ samba_server_shares | reversemultimap('path', 'users', 'user') | map(attribute='user') | maplistwithlistlookup('user', samba_server_share_users, 'user') }}"

- name: Add Share Group to Share Users
  user:
    groups: "{{ item.group }}"
    name: "{{ item.user.user }}"
    append: yes
  loop: "{{ samba_server_shares | reversemultimap('group', 'users', 'user') }}"

# TODO Secrets Secrets...  Manual password change after for now
- name: Set Samba Passwords
  shell: "printf 'test\ntest\n' | smbpasswd -L -s -a {{item.user}}"
  loop: "{{ samba_server_shares | reversemultimap('path', 'users', 'user') | map(attribute='user') | maplistwithlistlookup('user', samba_server_share_users, 'user') }}"
  register: test

- name: Open UFW Ports
  include_role:
    name: ufw_open_ports
  vars:
    ufw_open_ports_ports:
      - '445'
      - '135'
      - '136'
      - '137'

- name: Create Samba Share Folders
  file:
    path: "{{ item.path }}"
    state: directory
    owner: nobody
    group: "{{ item.group }}"
    mode: g+rw
  loop: "{{ samba_server_shares }}"
  notify:
    - smbd | restart

- name: Generate Configuration for Samba Config
  template:
    src: templates/smb.conf.j2
    dest: /etc/samba/smb.conf
    mode: u+r
  vars:
    shares: "{{ samba_server_shares }}"
  notify:
    - smbd | restart
