ansible_host: 142.93.147.44

application_jellyfin_config:
  friendly_name: jellyfin
  repo: git@github.com:DalinSeivewright/application_jellyfin.git
  networks:
    internal-proxy:
      type: external
  containers:
    jellyfin:
      image: linuxserver/jellyfin
      restart: unless-stopped
      networks:
        internal-proxy:
      uid: 911
      gid: 911
      volumes:
        - source: config
          dest: /config
          relative: yes
        - source: /mnt/volume_tor1_01/music
          dest: /data/music:ro
          relative: no
      proxy:
        server: music.logichromatic.ca
        delegate_host: droplet-jellyfin
        container_port: "8080"
        self_signed: no
