ansible_host: 192.168.1.206
feature_interactive_user: yes
nfs_server:
  exports:
    - path: /mnt/md1/test
      users:
        - user: backup_user
          group: backup_user
          permissions: rwx