- name: Update and Upgrade
  include_role:
    name: update_upgrade

- name: Install pip3
  apt:
    name: python3-pip
    state: present

- name: Enable UFW and Default rules
  include_role:
    name: ufw_default
