- name: Install BOINC
  apt:
    name:
    - boinc-client
    state: latest
  when: installing

- name: Open Remote Control Port
  include_role:
    name: ufw_open_ports
  vars:
    ufw_open_ports_ports:
      - "31416"
  when: installing

- name: Generate Configuration for Boinc Client
  template:
    src: templates/cc_config.xml.j2
    dest: /var/lib/boinc-client/cc_config.xml
    mode: u+r
  notify:
    - boinc | restart

- name: Generate Configuration for Boinc Client Preference Overrides
  template:
    src: templates/global_prefs_override.xml.j2
    dest: /var/lib/boinc-client/global_prefs_override.xml
    mode: u+r
  notify:
    - boinc | restart
