neopixel_healthchecker_hosts: []
neopixel_healthchecker_status_file: /tmp/neopixel-healthchecker-statuses.json
neopixel_healthchecker_ping_timeout: 1
neopixel_healthchecker_pixel_count: 16
neopixel_healthchecker_colors:
  alive:
    r: 1
    g: 1
    b: 1
  dead:
    r: 1
    g: 0
    b: 0
  updating:
    r: 0
    g: 0
    b: 1
