application_wger_config:
  friendly_name: wger
  repo: git@github.com:DalinSeivewright/application_wger.git
  networks:
    internal-proxy:
      type: external
  shared_gid: 1000
  shared_uid: 1000
  containers:
    web:
      image: wger/devel:2.0-dev
      restart: unless-stopped
      uid: 1000
      gid: 1000
      networks:
        internal-proxy:
      volumes:
        - source: media
          shared: true
          dest: /home/wger/media
        - source: static
          shared: true
          dest: /home/wger/static
      user: "1000:1000"
      depends_on:
        - db
        - cache
      environment:
        # Database
        DJANGO_DB_ENGINE: django.db.backends.postgresql
        DJANGO_DB_DATABASE: wger
        DJANGO_DB_USER: wger
        DJANGO_DB_PASSWORD: wger
        DJANGO_DB_HOST: db
        DJANGO_DB_PORT: 5432
        # Cache
        DJANGO_CACHE_BACKEND: django_redis.cache.RedisCache
        DJANGO_CACHE_LOCATION: redis://cache:6379/1
        DJANGO_CACHE_TIMEOUT: 1296000 # 60*60*24*15, 15 Days
        DJANGO_CACHE_CLIENT_CLASS: django_redis.client.DefaultClient
        DJANGO_MEDIA_ROOT: /home/wger/media
        # Set the secret key to a random string if you are running this instance publicly
        #SECRET_KEY = abcdef....
        # Application
        ALLOW_REGISTRATION: 'true'
        ALLOW_GUEST_USERS: 'true'
        # Others
        DJANGO_DEBUG: 'true'
        WGER_USE_GUNICORN: 'false'
        TIME_ZONE: America/Regina
        SITE_URL: http://melissa.oni.logichromatic.ca:8000
    nginx:
      image: nginx:1.19.0-alpine
      restart: unless-stopped
      networks:
        internal-proxy:
      ports:
        - "8000:80"
      volumes:
        - source: media
          shared: true
          dest: /wger/media
        - source: static
          shared: true
          dest: /wger/static
        - source: config/nginx.conf
          relative: true
          dest: /etc/nginx/conf.d/default.conf
      depends_on:
        - web
    db:
      image: postgres:12.0-alpine
      restart: unless-stopped
      networks:
        internal-proxy:
      volumes:
        - source: data
          dest: /var/lib/postgresql/data/
          relative: true
      environment:
        POSTGRES_USER: wger
        POSTGRES_PASSWORD: wger
        POSTGRES_DB: wger
    cache:
      image: redis:latest
      restart: unless-stopped
      networks:
        internal-proxy:
