omada_docker_folder: omada-controller
omada_repo: git@github.com:DalinSeivewright/application_omada.git

omada_reverse_proxy_server_name: omada.oni.logichromatic.ca
omada_reverse_proxy_host: melissa
omada_reverse_proxy_site_name: omada
omada_self_signed_certs: yes
omada_container_macvlan_network: yes
omada_container_proxy_host: 192.168.1.244

application_omada_config:
  friendly_name: omada
  repo: git@github.com:DalinSeivewright/application_omada.git
  networks:
    macvlan0:
      type: external
      driver: macvlan
  containers:
    omada:
      image: mbentley/omada-controller:4.1
      restart: unless-stopped
      uid: 508
      gid: 508
      environment:
        MANAGE_HTTP_PORT: 8088
        MANAGE_HTTPS_PORT: 8043
        PORTAL_HTTP_PORT: 8088
        PORTAL_HTTPS_PORT: 8843
        SHOW_SERVER_LOGS: 'true'
        SHOW_MONGODB_LOGS: 'false'
        TZ: America/Regina
      networks:
        macvlan0:
          ip: 192.168.1.244
      volumes:
        - source: data
          dest: /opt/tplink/EAPController/data
          relative: yes
        - source: work
          dest: /opt/tplink/EAPController/work
        - source: logs
          dest: /opt/tplink/EAPController/logs
