jellyfin_docker_folder: jellyfin
jellyfin_repo: git@github.com:DalinSeivewright/application_jellyfin.git
jellyfin_extra_mounts:
  - /mnt/md1/shares/music:/data/music:ro
  - /mnt/md1/shares/movies:/data/movies:ro
  - /mnt/md1/shares/tv:/data/tv:ro
  - /mnt/md1/shares/videos:/data/videos:ro
jellyfin_reverse_proxy_server_name: music.oni.logichromatic.ca
jellyfin_reverse_proxy_host: melissa
jellyfin_reverse_proxy_site_name: music
jellyfin_self_signed_certs: yes

application_name: jellyfin
application_docker_folder: jellyfin
application_repo: git@github.com:DalinSeivewright/application_jellyfin.git
application_reverse_proxy_server_name: music.oni.logichromatic.ca
application_reverse_proxy_host: melissa
application_reverse_proxy_site_name: music
application_self_signed_certs: yes

application_jellyfin_config:
  friendly_name: jellyfin
  repo: git@github.com:DalinSeivewright/application_jellyfin.git
  networks:
    internal-proxy:
      type: external
  containers:
    jellyfin:
      image: linuxserver/jellyfin
      restart: unless-stopped
      networks:
        internal-proxy:
      uid: 911
      gid: 911
      volumes:
        - source: config
          dest: /config
          relative: yes
        - source: /mnt/md1/shares/music
          dest: /data/music:ro
          relative: no
        - source: /mnt/md1/shares/movies
          dest: /data/movies:ro
          relative: no
        - source: /mnt/md1/shares/tv
          dest: /data/tv:ro
          relative: no
        - source: /mnt/md1/shares/videos
          dest: /data/videos:ro
          relative: no
      proxy:
        server: music.oni.logichromatic.ca
        delegate_host: melissa
        container_port: "8080"
        self_signed: yes
