
- name: Install Python3
  apt:
    name: python3
    state: latest
    force_apt_get: yes
    update_cache: no

- name: Install Python3 Pip3
  apt:
    name: python3-pip
    state: latest
    force_apt_get: yes
    update_cache: no

- name: Install Neopixel Healthecker
  pip:
    name:
      - git+https://github.com/DalinSeivewright/neopixel-healthchecker.git

- name: Create Neopixel Health Checker folder
  file:
    path: "/home/{{provision_user}}/.healthchecker/"
    state: directory

- name: Create health check script config file
  template:
    src: templates/neopixel-healthchecker.json.j2
    dest: "/home/{{provision_user}}/.healthchecker/neopixel-healthchecker.json"
    mode: u+r
  vars:
    servers: "{{healthchecker_hosts}}"
    timeout: "{{healthchecker_ping_timeout}}"
    file: "{{healthchecker_status_file}}"
    pixels: "{{healthchecker_pixel_count}}"

- name: Add cron job for health checker
  cron:
    name: "Neopixel Healthchecker"
    job: "python3 /home/{{provision_user}}/.local/bin/neopixel-healthchecker.py -c /home/{{provision_user}}/.healthchecker/neopixel-healthchecker.json"
    state: present
