- name: Install Atom
  apt:
    install_recommends: no
    state: present
    deb: https://atom.io/download/deb
  when: "installing == true"

- name: Remove Atom
  apt:
    state: absent
    autoremove: yes
    name:
      - atom
  when: "installing == false"
