- hosts: boinc_einstein
  gather_facts: no
  become: yes
  tasks:
  - name: Control Einstein
    shell: "boinccmd --project {{boinc_attach_project_project_name}} {{boinc_op}}"
    register: attach_cmd
    failed_when: "attach_cmd.rc != 0"
    args:
      executable: /bin/bash
    vars:
      boinc_attach_project_project_name: "{{einstein_project_name}}"
  vars:
    ansible_user: "{{ provision_user }}"
    ansible_ssh_private_key_file: "{{ provision_private_key | realpath }}"
