- hosts: "{{ new_hosts }}"
  gather_facts: no
  become: yes
  tasks:
  - name: Base Rasbian Setup
    include_role:
      name: rasbian
    # Remember to change this
    when: "'rasbian' in group_names"
  - name: Provision DNS Service
    include_role:
      name: dns
    when: "'dns' in group_names"
  vars:
      ansible_user: "{{ provision_user }}"
      ansible_ssh_private_key_file: "{{ provision_private_key | realpath }}"
