- hosts: "{{target_host}}"
  gather_facts: no
  become: yes
  tasks:
  - name: Add Interactive User
    include_role:
      name: add_interactive_user
    when: "{{feature_interactive_user}}"
    vars:
      interactive_user: "{{ interactive_user }}"
      interactive_group: "{{ interactive_group }}"
      interactive_password: "{{ interactive_password }}"
      interactive_public_key_path: "{{ provision_public_key | realpath }}"
      installing: "{{feature_interactive_user}}"
  vars:
      ansible_user: "{{ provision_user }}"
      ansible_ssh_private_key_file: "{{ provision_private_key | realpath }}"
