- hosts: "{{target_host}}"
  gather_facts: no
  become: yes
  tasks:
  - name: Add Interactive User
    include_role:
      name: interactive_user
    vars:
      new_user: "{{ interactive_user }}"
      new_group: "{{ interactive_group }}"
      new_password: "{{ interactive_password }}"
      new_public_key_path: "{{ provision_public_key | realpath }}"
  vars:
      ansible_user: "{{ provision_user }}"
      ansible_ssh_private_key_file: "{{ provision_private_key | realpath }}"
