- hosts: "neopixel_healthchecker"
  gather_facts: no
  become: yes
  tasks:
  - name: Setup Neopixel Healthchecker
    include_role:
      name: neopixel_healthchecker
  vars:
      ansible_user: "{{ provision_user }}"
      ansible_ssh_private_key_file: "{{ provision_private_key | realpath }}"
