- hosts: all
  gather_facts: no
  strategy: free
  become: yes
  tasks:
  - name: reboot
    reboot:
  vars:
    ansible_user: "{{ provision_user }}"
    ansible_ssh_private_key_file: "{{ provision_private_key | realpath }}"
