- hosts: "reverse_proxy"
  gather_facts: no
  become: yes
  tasks:
  - name: Check Docker
    become: yes
    command: "docker --version"
    ignore_errors: yes
    register: docker_result
    changed_when: False

  - name: Ensure docker host group and docker installed
    fail:
      msg: "{{ inventory_hostname }} must be part of the docker_host group and docker-provision.yml must have been run!"
    when: "'docker_host' not in group_names or docker_result is failed"

  - name: Grab Docker User Subuid Start Range
    command: "grep -Po 'docker-manager:\\K[0-9]+' /etc/subuid"
    register: docker_subuid_start

  - name: Clone Reverse Proxy Repo Project
    connection: local
    become: no
    git:
      repo : "{{ reverse_proxy_repo }}"
      dest : /tmp/nginx-reverse-proxy
      key_file: "{{ansible_ssh_private_key_file}}"

  - name: Create reverse proxy docker volume folder
    file:
      path: "{{ docker_volume_path }}"
      state: directory

  - name: Create Config
    template:
      src: /tmp/nginx-reverse-proxy/nginx-compose.yml.j2
      dest: "{{ [docker_volume_path, 'nginx-compose.yml'] | path_join }}"
      mode: u+r
    vars:
      data_root: "{{ docker_volume_data_path }}"
    notify: nginx reverse proxy | restart

  - name: Create Certs folder for Reverse Proxy Project
    connection: local
    become: no
    file:
      path: /tmp/nginx-reverse-proxy/config/ssl/certs
      state: directory
    notify: nginx reverse proxy | restart

  - name: Generate dhparam
    connection: local
    become: no
    openssl_dhparam:
      path: /tmp/nginx-reverse-proxy/config/ssl/certs/dhparam.pem
      size: 4096
    notify: nginx reverse proxy | restart

  - name: Create Default site cert folder for Reverse Proxy Project
    connection: local
    become: no
    file:
      path: /tmp/nginx-reverse-proxy/config/ssl/certs/default
      state: directory
    notify: nginx reverse proxy | restart

  - name: Generate private key
    connection: local
    become: no
    openssl_privatekey:
      path: /tmp/nginx-reverse-proxy/config/ssl/certs/default/default-selfsigned.key
      size: 4096
      type: RSA
    notify: nginx reverse proxy | restart

  - name: Generate CSR
    connection: local
    become: no
    openssl_csr:
      path: /tmp/nginx-reverse-proxy/config/ssl/certs/default/default-selfsigned.csr
      privatekey_path: /tmp/nginx-reverse-proxy/config/ssl/certs/default/default-selfsigned.key
      common_name: default
    notify: nginx reverse proxy | restart

  - name: Generate Default Certs
    connection: local
    become: no
    openssl_certificate:
      path: /tmp/nginx-reverse-proxy/config/ssl/certs/default/default-selfsigned.crt
      csr_path: /tmp/nginx-reverse-proxy/config/ssl/certs/default/default-selfsigned.csr
      privatekey_path: /tmp/nginx-reverse-proxy/config/ssl/certs/default/default-selfsigned.key
      provider: selfsigned
      selfsigned_not_after: "{{ ssl_cert_expire_date }}"
    notify: nginx reverse proxy | restart

  - name: Synchronize Required Files
    synchronize:
      src: /tmp/nginx-reverse-proxy/config
      dest: "{{ docker_volume_data_path }}"
      delete: no
      owner: no
      group: no
    notify: nginx reverse proxy | restart

  - name: Change ownerships to docker container user (whoever decided not to accept UID and GID with file needs to be reprimanded)
    command: "chown -R {{ (docker_subuid_start.stdout | int) + docker_container_user_uid }}:{{ (docker_subuid_start.stdout | int) + docker_container_user_gid }} {{ docker_volume_data_path | quote }}"

  - name: Create Docker Internal Proxy Network
    command: "docker network create internal-proxy"
    register: commandResult
    failed_when: " commandResult.rc != 0 and 'already exists' not in commandResult.stderr "
    notify: nginx reverse proxy | restart

  - name: Open UFW HTTP/S Ports
    include_role:
      name: ufw_open_ports
    vars:
      ufw_open_ports_ports:
        - '80'
        - '443'

  handlers:
    - name: nginx reverse proxy | restart
      command: "docker-compose -f {{[docker_volume_root, reverse_proxy_docker_folder, 'nginx-compose.yml'] | path_join | quote}} up -d --force-recreate"

  vars:
    docker_volume_path: "{{ [docker_volume_root, reverse_proxy_docker_folder] | path_join }}"
    docker_volume_data_path: "{{ [docker_volume_path, 'docker_data'] | path_join }}"
    ansible_user: "{{ provision_user }}"
    ansible_ssh_private_key_file: "{{ provision_private_key | realpath }}"
