- hosts: samba_server
  become: yes
  gather_facts: no
  tasks:
  - name: Setup Samba Server
    include_role:
      name: samba_server
    vars:
      samba_server_shares: "{{samba_server.shares}}"
      samba_server_share_groups: "{{share_groups}}"
      samba_server_share_users: "{{share_users}}"
  vars:
    ansible_user: "{{ provision_user }}"
    ansible_ssh_private_key_file: "{{ provision_private_key | realpath }}"
