- hosts: all
  gather_facts: no
  become: yes
  tasks:
  - name: Shutdown Host
    command: shutdown -h +1
  vars:
    ansible_user: "{{ provision_user }}"
    ansible_ssh_private_key_file: "{{ provision_private_key | realpath }}"
