- hosts: all
  gather_facts: no
  become: yes
  strategy: free
  tasks:
  - name: Update and Upgrade
    include_role:
      name: update_upgrade
  vars:
    ansible_user: "{{ provision_user }}"
    ansible_ssh_private_key_file: "{{ provision_private_key | realpath }}"
