- name: Install Power DNS Recursor Server
  apt:
    name: pdns-recursor
    state: latest
    force_apt_get: yes
    update_cache: no
  notify:
    - pdns-recursor | restart

- name: Generate Configuration for Recursor
  template:
    src: templates/recursor.conf.j2
    dest: /etc/powerdns/recursor.conf
    mode: u+r
  notify:
    - pdns-recursor | restart
